JS-Book-Library
jrai0792/Book-library pull request #1
Opened 2021-01-22 10:22 UTC by SajjadAhmad14

- User can add books to the library.
-  User can remove a book from the library.
-  User can change the read status of a book.

2021-01-22 11:10 UTC, elmejdki requested changes
# status: require changes :recycle: 
Great job guys, you have implemented all the necessary functionalities :1st_place_medal:  but there is some changes :hammer: :hammer_and_wrench: :toolbox: that you need to make in order to get this project approved :checkered_flag:

please check the comments below:
:point_down: :point_down: :point_down: :point_down: :point_down:

## Required Changes :red_circle::

- [ ] Fix the live demo link you used localhost :laughing:.

- [ ] it will be better if you made the Add book button toggle the form I mean, display it and hide it on clicks.
![image](https://user-images.githubusercontent.com/34653764/105482586-dd2e6b00-5ca8-11eb-8303-4f6fa1786c87.png)

- [ ] Keep the application logic separated from DOM manipulation tasks.
![image](https://user-images.githubusercontent.com/34653764/105483352-08658a00-5caa-11eb-8d22-c1a0b914bce4.png)

## Joyti Only Requirements :yum::
- [ ] Joyti I highly recommend that you create a Linkedin profile(a Twitter also if you can) now before tomorrow and start networking and connecting to new people cause it will be very helpful in your job search later.

## OPTIONAL:

- [ ] use localStorage to make the list of books persistent on page loads or much better try to use firebase it's really easy just give it a try.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_Feel free to contact me on slack if you have any questions or need help_
## _Zakariae El Mejdki_

2021-01-22 11:10 UTC, elmejdki commented on assets/script/main.js
> +}
- [ ] you should always write pure functions your constructors and methods should not rely on other variables, please use a constructor that takes parameters.

2021-01-22 11:12 UTC, elmejdki requested changes

2021-01-22 11:12 UTC, elmejdki commented on assets/script/main.js
> +}
- display book function should loop through all the books for the librarybooks variable and display them one by one.
![image](https://user-images.githubusercontent.com/34653764/105484034-05b76480-5cab-11eb-9886-6e775984b95c.png)

2021-01-24 22:52 UTC, Forison requested changes
## Status::Change required❌
# 🙋‍♂️ team
### Good job on addressing some of the issues raised in the previous review🤗.
* [ ] I could only add a book after I tried adding more books after the first it does not happen. The application freezes.
#### That is it kindly address the change and submit a re-review🤗
#### Happy coding

2021-01-25 06:24 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon:

Hi **TEAM** congratulations on this project :fireworks: Having fixed all the comments outlined by he previous TSE's :smile: I hereby approve the project :+1: 

Kindly merge into the development, do not forget to submit the project completions form
_Happy coding: :man_technologist: :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-01-25 07:03 UTC, merged